#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, Address, Env};

#[contracttype]
pub enum DataKey {
    SubContract,
}

// Import the SubscriptionContract client generated by soroban-sdk
mod subscription_contract {
    soroban_sdk::contractimport!(
        file = "../../target/wasm32-unknown-unknown/release/subscription.wasm"
    );
}

#[contract]
pub struct ContentGateContract;

#[contractimpl]
impl ContentGateContract {
    /// Store the address of the deployed SubscriptionContract.
    pub fn init(env: Env, subscription_contract: Address) {
        if env.storage().instance().has(&DataKey::SubContract) {
            panic!("already initialized");
        }
        env.storage()
            .instance()
            .set(&DataKey::SubContract, &subscription_contract);
        env.storage().instance().extend_ttl(6_307_200, 6_307_200);
    }

    /// Cross-contract call: returns true if `user` has an active subscription.
    pub fn check_access(env: Env, user: Address) -> bool {
        let sub_contract: Address = env
            .storage()
            .instance()
            .get(&DataKey::SubContract)
            .expect("not initialized");

        let client = subscription_contract::Client::new(&env, &sub_contract);
        client.is_active(&user)
    }
}

#[cfg(test)]
mod test;
